BUCKET: dashboard-dataset-metadata
DATASET_METADATA_FILENAME: dataset-metadata.json
DATASETS:
<<<<<<< Updated upstream
  STATIC:
  - taiga-forest-classification.json
  - ATL08.json
  - Landsat8.json
  - topo.json
=======
  - MOD13A1.006.json
  - modis-aod.json
>>>>>>> Stashed changes
