name: Generate & update the dataset json file in the s3 folder specified in config.yml
on:
  push:
    branches:
      - main
      - add-atl08 # will remove this repo once it's ready to be merged

jobs:
  run-metadata-generator:
    runs-on: ubuntu-latest
  
    steps:
      - name: Configure AWS credentials from MAAP AWS Account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.8'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute the metadata generator script
        run: python -m dataset_metadata_generator.src.main
